---
- name: Define pve_cluster_addr0 if not provided
  ansible.builtin.set_fact:
    pve_cluster_addr0: "{{ pve_cluster_addr0 | default(_pve_cluster_addr0) }}"

- name: Calculate list of SSH addresses
  ansible.builtin.set_fact:
    pve_cluster_ssh_addrs: >-
      ["{{ ansible_fqdn }}", "{{ ansible_hostname }}",
      "{{ pve_cluster_addr0 }}",
      {% if pve_cluster_addr1 is defined %}"{{ pve_cluster_addr1 }}"{% endif %}]

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure that facts are present for all cluster hosts
  ansible.builtin.assert:
    that:
      - "hostvars[item].ansible_facts"
    msg: "Could not load facts for {{ item }}. Please run your playbook against all hosts in {{ pve_group }}."
  with_items: "{{ groups[pve_group] }}"
  when: "pve_cluster_enabled | bool"

- name: Ensure this host is in the group specified
  ansible.builtin.assert:
    that:
      - "inventory_hostname in groups[pve_group]"
    msg: "This host does not appear to be in the group {{ pve_group }}, \
          did you specify the pve_group host variable correctly?"
  when: "pve_cluster_enabled | bool"

...
