---
- name: Create SSH directory for root
  ansible.builtin.file:
    path: /root/.ssh/
    state: directory
    mode: '0700'

- name: Create root SSH key pair for PVE
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_file: /root/.ssh/id_rsa
    ssh_key_type: rsa
    ssh_key_comment: "root@{{ inventory_hostname_short }}"

- name: Fetch root SSH public key
  ansible.builtin.slurp:
    src: /root/.ssh/id_rsa.pub
  register: proxmox_root_id_rsa_pub

- name: Authorize all hosts' root SSH public keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ hostvars[item].proxmox_root_id_rsa_pub.content | b64decode }}"
  with_items: "{{ groups[pve_group] }}"

- name: Configure SSH clients for connecting to PVE cluster hosts
  ansible.builtin.blockinfile:
    dest: /etc/ssh/ssh_config
    create: true
    mode: '0644'
    marker: "# {mark}: PVE host configuration options (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Host {{ hostvars[host].pve_cluster_ssh_addrs | join(" ") }}
          IdentityFile /root/.ssh/id_rsa
          Port {{ pve_ssh_port }}
      {% endfor %}

- name: Allow root logins from PVE cluster hosts
  ansible.builtin.blockinfile:
    dest: /etc/ssh/sshd_config.d/00_proxmox
    create: true
    mode: '0600'
    marker: "# {mark}: Allow root logins from PVE hosts (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Match Address {{ hostvars[host].pve_cluster_ssh_addrs | join(",") }}
      PermitRootLogin prohibit-password
      {% endfor %}
    validate: "/usr/sbin/sshd -t -f %s"
  notify:
    - reload sshd configuration

- name: Fetch SSH public host keys
  ansible.builtin.slurp:
    src: "/etc/ssh/{{ item }}"
  register: proxmox_ssh_public_host_keys
  with_items:
    - ssh_host_rsa_key.pub
    - ssh_host_ed25519_key.pub
    - ssh_host_ecdsa_key.pub

- name: Check status of known hosts file
  ansible.builtin.stat:
    path: /etc/ssh/ssh_known_hosts
  register: _pve_known_hosts_file

- name: Add every host's host keys to global known_hosts
  ansible.builtin.blockinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: true
    mode: '0644'
    marker: "# {mark}: PVE host keys (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      {% for _key_slurp in hostvars[host].proxmox_ssh_public_host_keys.results %}
      {%- set _key = ' '.join((_key_slurp.content | b64decode).split()[:-1]) -%}
      {{ hostvars[host].pve_cluster_ssh_addrs | join(",") }} {{ _key }}
      {% endfor %}
      {% endfor %}
  when:
    - "not (_pve_known_hosts_file.stat.islnk is defined and _pve_known_hosts_file.stat.islnk)"

- name: Add PVE-provided ciphers to SSH client config
  ansible.builtin.lineinfile:
    line: "Ciphers {{ pve_ssh_ciphers }}"
    regexp: "^Ciphers .*"
    insertbefore: BOF
    create: true
    mode: '0644'
    dest: /root/.ssh/config

- name: Run handlers if needed (sshd reload)
  ansible.builtin.meta: flush_handlers

...
