---
- name: Create ZFS Pools
  community.general.zfs:
    name: "{{ item.pool }}"
    state: present
  with_items: "{{ pve_storages }}"
  when: "item.type == 'zfspool'"

- name: Create ZFS Volumes specified by user
  community.general.zfs:
    name: "{{ item }}"
    state: present
  with_items: "{{ pve_zfs_create_volumes }}"

- name: Configure Proxmox Storage
  hcs_company.proxmox.proxmox_storage:
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    disable: "{{ item.disable | default(False) }}"
    path: "{{ item.path | default(omit) }}"
    content: "{{ item.content | default([]) }}"
    nodes: "{{ item.nodes | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    pool: "{{ item.pool | default(omit) }}"
    monhost: "{{ item.monhost | default(omit) }}"
    maxfiles: "{{ item.maxfiles | default(omit) }}"
    krbd: "{{ item.krbd | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    server: "{{ item.server | default(omit) }}"
    export: "{{ item.export | default(omit) }}"
    options: "{{ item.options | default(omit) }}"
    vgname: "{{ item.vgname | default(omit) }}"
    thinpool: "{{ item.thinpool | default(omit) }}"
    sparse: "{{ item.sparse | default(omit) }}"
  with_items: "{{ pve_storages }}"
  when: "not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == groups[pve_group][0])"

...
