---
- name: Set the VM ID of '{{ proxmox_vm_inventory_host }}' to a separate variable
  ansible.builtin.set_fact:
    _current_vmid: "{{ (_proxmox_created_vmids | selectattr('name','search',proxmox_vm_inventory_host) | list | first).vmid }}"

- name: Configure '{{ proxmox_vm_inventory_host }}' for Cloud-init
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_vm_hypervisor_user }}@{{ proxmox_vm_hypervisor_user_realm }}"
    api_password: "{{ proxmox_vm_hypervisor_user_password }}"
    api_host: "{{ proxmox_vm_hypervisor_api }}"
    name: "{{ proxmox_vm_inventory_host }}"
    vmid: "{{ _current_vmid }}"
    node: "{{ proxmox_vm_hypervisor }}"
    storage: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.storage }}"
    cicustom: "user={{ proxmox_vm_cloudinit_volume }}:snippets/{{ _current_vmid }}-cicustom_user.yml,network={{ proxmox_vm_cloudinit_volume }}:snippets/{{ _current_vmid }}-cicustom_network.yml,meta={{ proxmox_vm_cloudinit_volume }}:snippets/{{ _current_vmid }}-cicustom_meta.yml"
    agent: "{{ proxmox_vm_enable_qemu_agent | bool | default(true) }}"
    cores: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.cores }}"
    vcpus: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.vcpus }}"
    memory: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.memory_size }}"
    balloon: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.balloon }}"
    update: true
  delegate_to: localhost

- name: Resizing disk for '{{ proxmox_vm_inventory_host }}' if desired | resizing through API.
  ansible.builtin.uri:
    url: "https://{{ proxmox_vm_hypervisor_api }}/api2/json/nodes/{{ proxmox_vm_hypervisor }}/qemu/{{ _current_vmid }}/resize"
    method: PUT
    validate_certs: false
    headers:
      Cookie: "PVEAuthCookie={{ _proxmox_vm_api_auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ _proxmox_vm_api_auth.json.data.CSRFPreventionToken }}"
    body_format: form-urlencoded
    body:
      disk: scsi0
      size: "{{ hostvars[proxmox_vm_inventory_host].proxmox_vm.disk_size }}"
  when: proxmox_vm_resize_disk | bool
  delegate_to: localhost

...
